### ISSUE TITLE
Hooks in the cucumber results cause errors when parsing

### ISSUE THREAD

**Issue by jar145** [Hygieia/hygieia-jenkins-cucumber-collector#7]
**Affects:** 3.1.0-SNAPSHOT.

Hello,

I found an error that occurs when parsing the received cucumber results. In my situation, the hooks (the **Before** step in the example below) and whether they pass or fail are recorded in the results. Because of this the parser doesn't expect them and throws an error. The specific error I receive is as follows:

```
2020-06-18 11:00:36,430 [taskScheduler-1] ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.NullPointerException: null
	at com.capitalone.dashboard.collector.CucumberJsonToTestResultTransformer.parseStepAsTestCaseStep(CucumberJsonToTestResultTransformer.java:155) ~[classes/:na]
CucumberJsonToTestResultTransformer.java:155
	at com.capitalone.dashboard.collector.CucumberJsonToTestResultTransformer.parseScenarioAsTestCase(CucumberJsonToTestResultTransformer.java:107) ~[classes/:na]
CucumberJsonToTestResultTransformer.java:107
	at com.capitalone.dashboard.collector.CucumberJsonToTestResultTransformer.parseFeatureAsTestSuite(CucumberJsonToTestResultTransformer.java:62) ~[classes/:na]
CucumberJsonToTestResultTransformer.java:62
	at com.capitalone.dashboard.collector.CucumberJsonToTestResultTransformer.transformer(CucumberJsonToTestResultTransformer.java:41) ~[classes/:na]
CucumberJsonToTestResultTransformer.java:41
	at com.capitalone.dashboard.collector.CucumberJsonToTestResultTransformer.transformer(CucumberJsonToTestResultTransformer.java:1) ~[classes/:na]
CucumberJsonToTestResultTransformer.java:1
	at com.capitalone.dashboard.collector.DefaultJenkinsClient.getCapabilities(DefaultJenkinsClient.java:173) ~[classes/:na]
DefaultJenkinsClient.java:173
	at com.capitalone.dashboard.collector.DefaultJenkinsClient.getCucumberTestResult(DefaultJenkinsClient.java:265) ~[classes/:na]
DefaultJenkinsClient.java:265
	at com.capitalone.dashboard.collector.JenkinsCucumberTestCollectorTask.addNewTestSuites(JenkinsCucumberTestCollectorTask.java:200) ~[classes/:na]
JenkinsCucumberTestCollectorTask.java:200
	at com.capitalone.dashboard.collector.JenkinsCucumberTestCollectorTask.collect(JenkinsCucumberTestCollectorTask.java:91) ~[classes/:na]
JenkinsCucumberTestCollectorTask.java:91
	at com.capitalone.dashboard.collector.JenkinsCucumberTestCollectorTask.collect(JenkinsCucumberTestCollectorTask.java:25) ~[classes/:na]
JenkinsCucumberTestCollectorTask.java:25
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) ~[core-3.1.5.jar:na]
CollectorTask.java:63
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
DelegatingErrorHandlingRunnable.java:54
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
ReschedulingRunnable.java:81
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_252]
Executors.java:511
```

An example of the data that is being received (via protractor-cucumber) is as below:

```
[
  {
    "keyword": "Feature",
    "name": "Fill in a form",
    "line": 1,
    "id": "fill-in-a-form",
    "tags": [],
    "uri": "e2e/features/search.feature",
    "elements": [
      {
        "id": "fill-in-a-form;basic-example-test",
        "keyword": "Scenario",
        "line": 7,
        "name": "Basic example test",
        "tags": [
          {
            "name": "@TC-12",
            "line": 6
          },
          {
            "name": "@BasicScenario",
            "line": 6
          }
        ],
        "type": "scenario",
        "steps": [
          {
            "keyword": "Before",
            "hidden": true,
            "match": {
              "location": "e2e/support/hooks.ts:5"
            },
            "result": {
              "status": "passed",
              "duration": 1233000000
            }
          },
          {
            "arguments": [],
            "keyword": "Given ",
            "line": 4,
            "name": "I am on \"Home Page\" page",
            "match": {
              "location": "e2e/steps/form.steps.ts:11"
            },
            "result": {
              "status": "passed",
              "duration": 4000000
            }
          },
          ...
```

I have a fix for this already and am happy to make a pull request. I will just need permissions to make a branch. Let me know if you have any questions! :)

---

**Comment by rvema** [comment]
@jar145 please proceed by creating a PR for the same, We prefer fork-pull strategy for contributions.
